//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayTotpGT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrayTotp_Plugin_Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrayTotp_Plugin_Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrayTotpGT.TrayTotp_Plugin_Localization", typeof(TrayTotp_Plugin_Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Seed.
        /// </summary>
        internal static string setdef_string_TotpSeed_StringName {
            get {
                return ResourceManager.GetString("setdef_string_TotpSeed_StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Settings.
        /// </summary>
        internal static string setdef_string_TotpSettings_StringName {
            get {
                return ResourceManager.GetString("setdef_string_TotpSettings_StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy TOTP.
        /// </summary>
        internal static string strCopyTotp {
            get {
                return ResourceManager.GetString("strCopyTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is locked!.
        /// </summary>
        internal static string strDatabaseIsLocked {
            get {
                return ResourceManager.GetString("strDatabaseIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is not open!.
        /// </summary>
        internal static string strDatabaseNotOpen {
            get {
                return ResourceManager.GetString("strDatabaseNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string strHelp {
            get {
                return ResourceManager.GetString("strHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TOTP Seed found!.
        /// </summary>
        internal static string strNoTotpFound {
            get {
                return ResourceManager.GetString("strNoTotpFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strSettings {
            get {
                return ResourceManager.GetString("strSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string strSetup {
            get {
                return ResourceManager.GetString("strSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup TOTP.
        /// </summary>
        internal static string strSetupTotp {
            get {
                return ResourceManager.GetString("strSetupTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string strSpaceDashSpace {
            get {
                return ResourceManager.GetString("strSpaceDashSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Correction.
        /// </summary>
        internal static string strTimeCorrection {
            get {
                return ResourceManager.GetString("strTimeCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP.
        /// </summary>
        internal static string strTotp {
            get {
                return ResourceManager.GetString("strTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Totp Plugin.
        /// </summary>
        internal static string strTrayTotpPlugin {
            get {
                return ResourceManager.GetString("strTrayTotpPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, bad seed!.
        /// </summary>
        internal static string strWarningBadSeed {
            get {
                return ResourceManager.GetString("strWarningBadSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, bad settings!.
        /// </summary>
        internal static string strWarningBadSet {
            get {
                return ResourceManager.GetString("strWarningBadSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, bad URL?.
        /// </summary>
        internal static string strWarningBadUrl {
            get {
                return ResourceManager.GetString("strWarningBadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, no settings!.
        /// </summary>
        internal static string strWarningNotSet {
            get {
                return ResourceManager.GetString("strWarningNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, storage!.
        /// </summary>
        internal static string strWarningStorage {
            get {
                return ResourceManager.GetString("strWarningStorage", resourceCulture);
            }
        }
    }
}
